apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: luiscoco/myapp:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ConnectionStrings__DefaultConnection
          value: server=mysqlserver1974.mysql.database.azure.com;database=mysqldatabase;user=adminmysql;password=Luiscoco123456
        volumeMounts:
        - mountPath: /app/certificate.pfx
          name: cert-volume
          subPath: certificate.pfx
      volumes:
      - name: cert-volume
        secret:
          secretName: myapp-cert
